language: python

python:
  - "3.6"

branches:
  only:
    - master

addons:
  apt:
    update: true
    packages:
      - build-essential
      - gdal-bin
      - libgdal-dev

before_install:
  - pip install cython

install:
  - pip install -e .[test]

script:
  - python -m pytest --color=yes -v

after_success:
  - codecov

notifications:
  email: false
  slack:
    rooms:
      - dhigras:TPwMxNqVS9FeaTUJNZlMmL6i
    on_failure: change
    on_success: change
    on_pull_requests: false
