name: terracotta
channels:
    - conda-forge
    - defaults
    - conda-forge/label/dev
dependencies:
    - python=3.6
    - numpy
    - flask
    - click
    - pillow
    - matplotlib
    - boto3
    - mercantile
    - rasterio>=1.0rc1
    - cachetools
    - tqdm
    - toml
